import { lightTheme } from "./frontendTheme";
import type { AppLanguage } from "./frontendTranslations";

export type { AppLanguage, TranslationKey } from "./frontendTranslations";
export { languageOptions } from "./frontendTranslations";

export const FRONTEND_CONFIG_STORAGE_KEY = "mycopilot.frontend-config";

export const frontendConfig = {
  language: "zh-CN" satisfies AppLanguage,
  typography: {
    fontFamily:
      '-apple-system, BlinkMacSystemFont, "SF Pro Text", "SF Pro Display", "Segoe UI", Inter, ui-sans-serif, sans-serif',
    monoFontFamily: 'ui-monospace, "SFMono-Regular", SFMono-Regular, Menlo, Consolas, monospace',
    sidebar: {
      actionSize: "15.5px",
      sectionTitleSize: "14.5px",
      bodySize: "15.5px",
    },
    rightPanel: {
      titleSize: "16px",
      descriptionSize: "13px",
    },
    settings: {
      titleSize: "24px",
      navSize: "14px",
      bodySize: "15px",
      sectionTitleSize: "16px",
    },
    configuration: {
      titleSize: "28px",
      headingSize: "20px",
      labelSize: "17px",
      controlSize: "18px",
      tableSize: "19px",
    },
    chat: {
      titleMinSize: "30px",
      titlePreferredSize: "4vw",
      titleMaxSize: "42px",
      inputSize: "17px",
      toolbarSize: "15px",
      messageSize: "16px",
      assistantSize: "17px",
      activitySize: "16px",
      activityDetailSize: "15px",
      metadataSize: "13px",
    },
    scale: {
      xs: "13px",
      sm: "14px",
      md: "15px",
      base: "16px",
      lg: "17px",
      xl: "18px",
      "2xl": "20px",
      "3xl": "21px",
      "4xl": "23px",
      dialogTitle: "26px",
      dialogTitleLarge: "30px",
      closeButton: "34px",
    },
    weight: {
      light: "300",
      regular: "500",
      control: "450",
      medium: "520",
      contentMedium: "540",
      semibold: "560",
      bold: "600",
      sectionStrong: "640",
      strong: "650",
      select: "660",
      heavy: "700",
      black: "720",
      extraBlack: "740",
      display: "760",
    },
    lineHeight: {
      none: "1",
      tight: "1.1",
      compact: "1.2",
      normal: "1.3",
      relaxed: "1.45",
      body: "1.58",
      roomy: "1.7",
      sidebar: "20px",
      control: "24px",
      title: "32px",
      sidebarTitle: "26px",
      rightTitle: "22px",
      rightDescription: "18px",
      dialogClose: "30px",
      cardTitle: "1.35",
      dialogBody: "1.4",
      settingsBody: "1.75",
      metadata: "1.25",
    },
  },
  colors: lightTheme.colors,
  radius: {
    none: "0",
    xxs: "3px",
    xs: "7px",
    sm: "8px",
    md: "9px",
    lg: "10px",
    xl: "11px",
    "2xl": "12px",
    control: "13px",
    row: "14px",
    card: "16px",
    popover: "18px",
    message: "21px",
    composer: "24px",
    dialog: "28px",
    pill: "999px",
  },
  shadow: lightTheme.shadow,
  effect: {
    blurSubtle: "blur(3px)",
    blurPopover: "blur(18px)",
    blurDialog: "blur(22px)",
  },
  icon: {
    size: {
      xs: "15px",
      sm: "16px",
      md: "17px",
      base: "18px",
      lg: "19px",
      xl: "20px",
      "2xl": "21px",
      "3xl": "22px",
      "4xl": "23px",
      "5xl": "24px",
    },
    stroke: {
      thin: "1.75",
      regular: "1.8",
      medium: "1.9",
      strong: "2",
      heavy: "2.3",
      black: "2.6",
      extraBlack: "2.8",
      ultra: "3",
    },
  },
  layout: {
    titlebarHeight: "52px",
    sidebarActionHeight: "34px",
    sidebarHeaderHeight: "32px",
    sidebarActionWidth: "28px",
    toolbarButtonSize: "32px",
    composerSubmitSize: "44px",
    settingsNavWidth: "clamp(286px, 23.8vw, 344px)",
  },
} as const;

export type FrontendConfig = typeof frontendConfig;

export function getFrontendCssVariables(config: FrontendConfig = frontendConfig): Record<string, string> {
  return {
    "--mc-font-family": config.typography.fontFamily,
    "--mc-mono-font-family": config.typography.monoFontFamily,

    "--mc-font-size-sidebar-action": config.typography.sidebar.actionSize,
    "--mc-font-size-sidebar-section-title": config.typography.sidebar.sectionTitleSize,
    "--mc-font-size-sidebar-body": config.typography.sidebar.bodySize,
    "--mc-font-size-right-panel-title": config.typography.rightPanel.titleSize,
    "--mc-font-size-right-panel-description": config.typography.rightPanel.descriptionSize,
    "--mc-font-size-settings-title": config.typography.settings.titleSize,
    "--mc-font-size-settings-nav": config.typography.settings.navSize,
    "--mc-font-size-settings-body": config.typography.settings.bodySize,
    "--mc-font-size-settings-section-title": config.typography.settings.sectionTitleSize,
    "--mc-font-size-configuration-title": config.typography.configuration.titleSize,
    "--mc-font-size-configuration-heading": config.typography.configuration.headingSize,
    "--mc-font-size-configuration-label": config.typography.configuration.labelSize,
    "--mc-font-size-configuration-control": config.typography.configuration.controlSize,
    "--mc-font-size-configuration-table": config.typography.configuration.tableSize,
    "--mc-font-size-chat-title-min": config.typography.chat.titleMinSize,
    "--mc-font-size-chat-title-preferred": config.typography.chat.titlePreferredSize,
    "--mc-font-size-chat-title-max": config.typography.chat.titleMaxSize,
    "--mc-font-size-chat-input": config.typography.chat.inputSize,
    "--mc-font-size-chat-toolbar": config.typography.chat.toolbarSize,
    "--mc-font-size-chat-message": config.typography.chat.messageSize,
    "--mc-font-size-chat-assistant": config.typography.chat.assistantSize,
    "--mc-font-size-chat-activity": config.typography.chat.activitySize,
    "--mc-font-size-chat-activity-detail": config.typography.chat.activityDetailSize,
    "--mc-font-size-chat-metadata": config.typography.chat.metadataSize,
    "--mc-font-size-xs": config.typography.scale.xs,
    "--mc-font-size-sm": config.typography.scale.sm,
    "--mc-font-size-md": config.typography.scale.md,
    "--mc-font-size-base": config.typography.scale.base,
    "--mc-font-size-lg": config.typography.scale.lg,
    "--mc-font-size-xl": config.typography.scale.xl,
    "--mc-font-size-2xl": config.typography.scale["2xl"],
    "--mc-font-size-3xl": config.typography.scale["3xl"],
    "--mc-font-size-4xl": config.typography.scale["4xl"],
    "--mc-font-size-dialog-title": config.typography.scale.dialogTitle,
    "--mc-font-size-dialog-title-large": config.typography.scale.dialogTitleLarge,
    "--mc-font-size-close-button": config.typography.scale.closeButton,
    "--mc-font-weight-light": config.typography.weight.light,
    "--mc-font-weight-regular": config.typography.weight.regular,
    "--mc-font-weight-control": config.typography.weight.control,
    "--mc-font-weight-medium": config.typography.weight.medium,
    "--mc-font-weight-content-medium": config.typography.weight.contentMedium,
    "--mc-font-weight-semibold": config.typography.weight.semibold,
    "--mc-font-weight-bold": config.typography.weight.bold,
    "--mc-font-weight-section-strong": config.typography.weight.sectionStrong,
    "--mc-font-weight-strong": config.typography.weight.strong,
    "--mc-font-weight-select": config.typography.weight.select,
    "--mc-font-weight-heavy": config.typography.weight.heavy,
    "--mc-font-weight-black": config.typography.weight.black,
    "--mc-font-weight-extra-black": config.typography.weight.extraBlack,
    "--mc-font-weight-display": config.typography.weight.display,
    "--mc-line-height-none": config.typography.lineHeight.none,
    "--mc-line-height-tight": config.typography.lineHeight.tight,
    "--mc-line-height-compact": config.typography.lineHeight.compact,
    "--mc-line-height-normal": config.typography.lineHeight.normal,
    "--mc-line-height-relaxed": config.typography.lineHeight.relaxed,
    "--mc-line-height-body": config.typography.lineHeight.body,
    "--mc-line-height-roomy": config.typography.lineHeight.roomy,
    "--mc-line-height-sidebar": config.typography.lineHeight.sidebar,
    "--mc-line-height-control": config.typography.lineHeight.control,
    "--mc-line-height-title": config.typography.lineHeight.title,
    "--mc-line-height-sidebar-title": config.typography.lineHeight.sidebarTitle,
    "--mc-line-height-right-title": config.typography.lineHeight.rightTitle,
    "--mc-line-height-right-description": config.typography.lineHeight.rightDescription,
    "--mc-line-height-dialog-close": config.typography.lineHeight.dialogClose,
    "--mc-line-height-card-title": config.typography.lineHeight.cardTitle,
    "--mc-line-height-dialog-body": config.typography.lineHeight.dialogBody,
    "--mc-line-height-settings-body": config.typography.lineHeight.settingsBody,
    "--mc-line-height-metadata": config.typography.lineHeight.metadata,

    "--mc-color-text-primary": config.colors.text.primary,
    "--mc-color-text-strong": config.colors.text.strong,
    "--mc-color-text-secondary": config.colors.text.secondary,
    "--mc-color-text-muted": config.colors.text.muted,
    "--mc-color-text-subtle": config.colors.text.subtle,
    "--mc-color-text-inverse": config.colors.text.inverse,
    "--mc-color-text-danger": config.colors.text.danger,
    "--mc-color-text-accent": config.colors.text.accent,
    "--mc-color-icon-default": config.colors.icon.default,
    "--mc-color-icon-muted": config.colors.icon.muted,
    "--mc-color-icon-subtle": config.colors.icon.subtle,
    "--mc-color-icon-accent": config.colors.icon.accent,
    "--mc-color-icon-danger": config.colors.icon.danger,
    "--mc-color-icon-success": config.colors.icon.success,
    "--mc-color-surface-app": config.colors.surface.app,
    "--mc-color-surface-left-panel": config.colors.surface.leftPanel,
    "--mc-color-surface-main-panel": config.colors.surface.mainPanel,
    "--mc-color-surface-right-panel": config.colors.surface.rightPanel,
    "--mc-color-surface-settings-nav": config.colors.surface.settingsNav,
    "--mc-color-surface-elevated": config.colors.surface.elevated,
    "--mc-color-surface-muted": config.colors.surface.muted,
    "--mc-color-surface-selected": config.colors.surface.selected,
    "--mc-color-surface-selected-subtle": config.colors.surface.selectedSubtle,
    "--mc-color-surface-info-subtle": config.colors.surface.infoSubtle,
    "--mc-color-surface-success-subtle": config.colors.surface.successSubtle,
    "--mc-color-surface-neutral-subtle": config.colors.surface.neutralSubtle,
    "--mc-color-surface-disabled": config.colors.surface.disabled,
    "--mc-color-surface-danger-subtle": config.colors.surface.dangerSubtle,
    "--mc-color-surface-danger-subtle-hover": config.colors.surface.dangerSubtleHover,
    "--mc-color-surface-danger-soft": config.colors.surface.dangerSoft,
    "--mc-color-surface-error-subtle": config.colors.surface.errorSubtle,
    "--mc-color-surface-glass": config.colors.surface.glass,
    "--mc-color-surface-glass-strong": config.colors.surface.glassStrong,
    "--mc-color-surface-glass-input": config.colors.surface.glassInput,
    "--mc-color-border-hairline": config.colors.border.hairline,
    "--mc-color-border-subtle": config.colors.border.subtle,
    "--mc-color-border-default": config.colors.border.default,
    "--mc-color-border-strong": config.colors.border.strong,
    "--mc-color-border-error": config.colors.border.error,
    "--mc-color-button-primary-bg": config.colors.button.primaryBg,
    "--mc-color-button-primary-bg-hover": config.colors.button.primaryBgHover,
    "--mc-color-button-primary-text": config.colors.button.primaryText,
    "--mc-color-button-secondary-bg": config.colors.button.secondaryBg,
    "--mc-color-button-secondary-bg-hover": config.colors.button.secondaryBgHover,
    "--mc-color-button-secondary-text": config.colors.button.secondaryText,
    "--mc-color-button-danger-bg": config.colors.button.dangerBg,
    "--mc-color-button-danger-bg-hover": config.colors.button.dangerBgHover,
    "--mc-color-button-danger-text": config.colors.button.dangerText,
    "--mc-color-button-danger-soft-text": config.colors.button.dangerSoftText,
    "--mc-color-button-danger-soft-bg": config.colors.button.dangerSoftBg,
    "--mc-color-button-danger-soft-bg-hover": config.colors.button.dangerSoftBgHover,
    "--mc-color-state-hover": config.colors.state.hover,
    "--mc-color-state-active": config.colors.state.active,
    "--mc-color-focus-ring": config.colors.state.focusRing,
    "--mc-color-focus-shadow": config.colors.state.focusShadow,
    "--mc-color-resize-handle": config.colors.state.resizeHandle,
    "--mc-color-overlay": config.colors.state.overlay,
    "--mc-color-overlay-light": config.colors.state.overlayLight,
    "--mc-radius-none": config.radius.none,
    "--mc-radius-xxs": config.radius.xxs,
    "--mc-radius-xs": config.radius.xs,
    "--mc-radius-sm": config.radius.sm,
    "--mc-radius-md": config.radius.md,
    "--mc-radius-lg": config.radius.lg,
    "--mc-radius-xl": config.radius.xl,
    "--mc-radius-2xl": config.radius["2xl"],
    "--mc-radius-control": config.radius.control,
    "--mc-radius-row": config.radius.row,
    "--mc-radius-card": config.radius.card,
    "--mc-radius-popover": config.radius.popover,
    "--mc-radius-message": config.radius.message,
    "--mc-radius-composer": config.radius.composer,
    "--mc-radius-dialog": config.radius.dialog,
    "--mc-radius-pill": config.radius.pill,
    "--mc-shadow-none": config.shadow.none,
    "--mc-shadow-hairline": config.shadow.hairline,
    "--mc-shadow-focus": config.shadow.focus,
    "--mc-shadow-composer": config.shadow.composer,
    "--mc-shadow-popover": config.shadow.popover,
    "--mc-shadow-popover-large": config.shadow.popoverLarge,
    "--mc-shadow-sidebar-menu": config.shadow.sidebarMenu,
    "--mc-shadow-card": config.shadow.card,
    "--mc-shadow-dialog": config.shadow.dialog,
    "--mc-effect-blur-subtle": config.effect.blurSubtle,
    "--mc-effect-blur-popover": config.effect.blurPopover,
    "--mc-effect-blur-dialog": config.effect.blurDialog,
    "--mc-icon-size-xs": config.icon.size.xs,
    "--mc-icon-size-sm": config.icon.size.sm,
    "--mc-icon-size-md": config.icon.size.md,
    "--mc-icon-size-base": config.icon.size.base,
    "--mc-icon-size-lg": config.icon.size.lg,
    "--mc-icon-size-xl": config.icon.size.xl,
    "--mc-icon-size-2xl": config.icon.size["2xl"],
    "--mc-icon-size-3xl": config.icon.size["3xl"],
    "--mc-icon-size-4xl": config.icon.size["4xl"],
    "--mc-icon-size-5xl": config.icon.size["5xl"],
    "--mc-icon-stroke-thin": config.icon.stroke.thin,
    "--mc-icon-stroke-regular": config.icon.stroke.regular,
    "--mc-icon-stroke-medium": config.icon.stroke.medium,
    "--mc-icon-stroke-strong": config.icon.stroke.strong,
    "--mc-icon-stroke-heavy": config.icon.stroke.heavy,
    "--mc-icon-stroke-black": config.icon.stroke.black,
    "--mc-icon-stroke-extra-black": config.icon.stroke.extraBlack,
    "--mc-icon-stroke-ultra": config.icon.stroke.ultra,
    "--mc-layout-titlebar-height": config.layout.titlebarHeight,
    "--mc-layout-sidebar-action-height": config.layout.sidebarActionHeight,
    "--mc-layout-sidebar-header-height": config.layout.sidebarHeaderHeight,
    "--mc-layout-sidebar-action-width": config.layout.sidebarActionWidth,
    "--mc-layout-toolbar-button-size": config.layout.toolbarButtonSize,
    "--mc-layout-composer-submit-size": config.layout.composerSubmitSize,
    "--mc-layout-settings-nav-width": config.layout.settingsNavWidth,
  };
}
