export type AppLanguage = "zh-CN" | "en-US";

export const FRONTEND_CONFIG_STORAGE_KEY = "mycopilot.frontend-config";

export const languageOptions: Array<{ value: AppLanguage; label: string }> = [
  { value: "zh-CN", label: "中文" },
  { value: "en-US", label: "English" },
];

export const frontendConfig = {
  language: "zh-CN" satisfies AppLanguage,
  typography: {
    fontFamily:
      'Inter, ui-sans-serif, -apple-system, BlinkMacSystemFont, "SF Pro Text", "Segoe UI", sans-serif',
    monoFontFamily: 'ui-monospace, "SFMono-Regular", SFMono-Regular, Menlo, Consolas, monospace',
    sidebar: {
      actionSize: "15px",
      sectionTitleSize: "13px",
      bodySize: "14px",
    },
    rightPanel: {
      titleSize: "16px",
      descriptionSize: "13px",
    },
    settings: {
      titleSize: "24px",
      navSize: "14px",
      bodySize: "15px",
      sectionTitleSize: "16px",
    },
    configuration: {
      titleSize: "28px",
      headingSize: "20px",
      labelSize: "17px",
      controlSize: "18px",
      tableSize: "19px",
    },
    chat: {
      titleMinSize: "30px",
      titlePreferredSize: "4vw",
      titleMaxSize: "42px",
      inputSize: "17px",
      toolbarSize: "15px",
    },
  },
  colors: {
    text: {
      primary: "#202123",
      strong: "#111827",
      secondary: "#344255",
      muted: "#8b95a1",
      subtle: "#979ca4",
      inverse: "#ffffff",
      danger: "#b42318",
      accent: "#005eea",
    },
    icon: {
      default: "#25282d",
      muted: "#697381",
      subtle: "#8f949c",
      accent: "#005eea",
      danger: "#ff2a16",
      success: "#008768",
    },
    surface: {
      app: "#f7f7f6",
      leftPanel: "#f5f6f7",
      mainPanel: "#fbfbfa",
      rightPanel: "#f8f8f7",
      settingsNav: "#f6f6f7",
      elevated: "#ffffff",
      muted: "#f3f4f5",
      selected: "#e9eaec",
      selectedSubtle: "#f1f2f4",
      infoSubtle: "#eef8ff",
      successSubtle: "#dcfaee",
      neutralSubtle: "#f3f4f6",
    },
    border: {
      hairline: "rgba(24, 24, 27, 0.08)",
      subtle: "rgba(31, 35, 41, 0.08)",
      default: "#d4dde8",
      strong: "#cdd6e1",
    },
    button: {
      primaryBg: "#142231",
      primaryBgHover: "#1d3044",
      primaryText: "#ffffff",
      secondaryBg: "#ffffff",
      secondaryBgHover: "#f8fafc",
      secondaryText: "#1f2d3d",
      dangerBg: "#d92d20",
      dangerBgHover: "#b42318",
      dangerText: "#ffffff",
    },
    state: {
      hover: "rgba(31, 35, 41, 0.055)",
      active: "rgba(31, 35, 41, 0.075)",
      focusRing: "rgba(45, 105, 210, 0.5)",
    },
  },
} as const;

export type FrontendConfig = typeof frontendConfig;

export function getFrontendCssVariables(config: FrontendConfig = frontendConfig): Record<string, string> {
  return {
    "--mc-font-family": config.typography.fontFamily,
    "--mc-mono-font-family": config.typography.monoFontFamily,

    "--mc-font-size-sidebar-action": config.typography.sidebar.actionSize,
    "--mc-font-size-sidebar-section-title": config.typography.sidebar.sectionTitleSize,
    "--mc-font-size-sidebar-body": config.typography.sidebar.bodySize,
    "--mc-font-size-right-panel-title": config.typography.rightPanel.titleSize,
    "--mc-font-size-right-panel-description": config.typography.rightPanel.descriptionSize,
    "--mc-font-size-settings-title": config.typography.settings.titleSize,
    "--mc-font-size-settings-nav": config.typography.settings.navSize,
    "--mc-font-size-settings-body": config.typography.settings.bodySize,
    "--mc-font-size-settings-section-title": config.typography.settings.sectionTitleSize,
    "--mc-font-size-configuration-title": config.typography.configuration.titleSize,
    "--mc-font-size-configuration-heading": config.typography.configuration.headingSize,
    "--mc-font-size-configuration-label": config.typography.configuration.labelSize,
    "--mc-font-size-configuration-control": config.typography.configuration.controlSize,
    "--mc-font-size-configuration-table": config.typography.configuration.tableSize,
    "--mc-font-size-chat-title-min": config.typography.chat.titleMinSize,
    "--mc-font-size-chat-title-preferred": config.typography.chat.titlePreferredSize,
    "--mc-font-size-chat-title-max": config.typography.chat.titleMaxSize,
    "--mc-font-size-chat-input": config.typography.chat.inputSize,
    "--mc-font-size-chat-toolbar": config.typography.chat.toolbarSize,

    "--mc-color-text-primary": config.colors.text.primary,
    "--mc-color-text-strong": config.colors.text.strong,
    "--mc-color-text-secondary": config.colors.text.secondary,
    "--mc-color-text-muted": config.colors.text.muted,
    "--mc-color-text-subtle": config.colors.text.subtle,
    "--mc-color-text-inverse": config.colors.text.inverse,
    "--mc-color-text-danger": config.colors.text.danger,
    "--mc-color-text-accent": config.colors.text.accent,
    "--mc-color-icon-default": config.colors.icon.default,
    "--mc-color-icon-muted": config.colors.icon.muted,
    "--mc-color-icon-subtle": config.colors.icon.subtle,
    "--mc-color-icon-accent": config.colors.icon.accent,
    "--mc-color-icon-danger": config.colors.icon.danger,
    "--mc-color-icon-success": config.colors.icon.success,
    "--mc-color-surface-app": config.colors.surface.app,
    "--mc-color-surface-left-panel": config.colors.surface.leftPanel,
    "--mc-color-surface-main-panel": config.colors.surface.mainPanel,
    "--mc-color-surface-right-panel": config.colors.surface.rightPanel,
    "--mc-color-surface-settings-nav": config.colors.surface.settingsNav,
    "--mc-color-surface-elevated": config.colors.surface.elevated,
    "--mc-color-surface-muted": config.colors.surface.muted,
    "--mc-color-surface-selected": config.colors.surface.selected,
    "--mc-color-surface-selected-subtle": config.colors.surface.selectedSubtle,
    "--mc-color-surface-info-subtle": config.colors.surface.infoSubtle,
    "--mc-color-surface-success-subtle": config.colors.surface.successSubtle,
    "--mc-color-surface-neutral-subtle": config.colors.surface.neutralSubtle,
    "--mc-color-border-hairline": config.colors.border.hairline,
    "--mc-color-border-subtle": config.colors.border.subtle,
    "--mc-color-border-default": config.colors.border.default,
    "--mc-color-border-strong": config.colors.border.strong,
    "--mc-color-button-primary-bg": config.colors.button.primaryBg,
    "--mc-color-button-primary-bg-hover": config.colors.button.primaryBgHover,
    "--mc-color-button-primary-text": config.colors.button.primaryText,
    "--mc-color-button-secondary-bg": config.colors.button.secondaryBg,
    "--mc-color-button-secondary-bg-hover": config.colors.button.secondaryBgHover,
    "--mc-color-button-secondary-text": config.colors.button.secondaryText,
    "--mc-color-button-danger-bg": config.colors.button.dangerBg,
    "--mc-color-button-danger-bg-hover": config.colors.button.dangerBgHover,
    "--mc-color-button-danger-text": config.colors.button.dangerText,
    "--mc-color-state-hover": config.colors.state.hover,
    "--mc-color-state-active": config.colors.state.active,
    "--mc-color-focus-ring": config.colors.state.focusRing,
  };
}

export const zhCNTranslations = {
  "app.mainWorkspace": "主工作区",
  "app.leftSidebar": "左侧栏",
  "app.rightSidebar": "右侧栏",
  "app.collapseLeftSidebar": "折叠左侧栏",
  "app.expandLeftSidebar": "展开左侧栏",
  "app.collapseRightSidebar": "折叠右侧栏",
  "app.expandRightSidebar": "展开右侧栏",
  "app.resizeLeftSidebar": "调整左侧栏宽度",
  "app.resizeRightSidebar": "调整右侧栏宽度",

  "sidebar.newConversation": "新对话",
  "sidebar.projects": "项目",
  "sidebar.conversations": "对话",
  "sidebar.emptyConversations": "暂无聊天",
  "sidebar.settings": "设置",
  "sidebar.moreConversationActions": "更多对话操作",
  "sidebar.newConversationAction": "建立新对话",
  "sidebar.justNow": "刚刚",
  "project.chooseProject": "Choose project",
  "project.searchProject": "搜索项目",
  "project.newProject": "New project",
  "project.noProject": "不使用项目",
  "project.folderInput": "选择本地项目文件夹",
  "project.moreActions": "更多项目操作",
  "project.newProjectConversation": "在项目中新建对话",

  "rightSidebar.newPanel": "新建面板",
  "rightSidebar.maximize": "最大化右侧栏",
  "rightSidebar.tools": "右侧栏工具",
  "rightSidebar.review": "审查",
  "rightSidebar.reviewDescription": "查看拟议编辑和变更集",
  "rightSidebar.terminal": "终端",
  "rightSidebar.terminalDescription": "在当前工作区中运行命令",

  "settings.navigation": "设置导航",
  "settings.backToApp": "返回应用",
  "settings.search": "搜索设置",
  "settings.searchPlaceholder": "搜索设置...",
  "settings.content": "设置内容",
  "settings.update": "更新",
  "settings.group.personal": "个人",
  "settings.group.coding": "编码",
  "settings.page.general": "常规",
  "settings.page.appearance": "外观",
  "settings.page.configuration": "配置",
  "settings.page.usageBilling": "使用情况和计费",
  "settings.page.environment": "环境",

  "general.language": "语言",
  "general.languageDescription": "配置软件前端显示的语言。",
  "general.languageAria": "软件语言",

  "appearance.description": "这里先保留外观设置页的文字骨架。后续可以放主题、字体、布局密度和界面显示偏好。",
  "environment.selectProject": "选择项目",
  "environment.addProject": "添加项目",
  "environment.deleteProject": "删除项目",
  "environment.folderInput": "选择本地项目文件夹",
  "environment.removeProjectTitle": "移除 {projectName}?",
  "environment.removeProjectDescription": "这将移除该项目。磁盘上的文件不会被删除。",
  "environment.cancelRemoveProject": "取消",
  "environment.confirmRemoveProject": "移除",
  "usageBilling.description": "这里先保留使用情况和计费页面的文字骨架。后续可以展示调用量、额度、账单和订阅状态。",

  "chat.newConversation": "新对话",
  "chat.title": "我们应该构建什么？",
  "chat.composer": "新对话输入框",
  "chat.inputPlaceholder": "随心输入",
  "chat.inputAria": "输入新任务",
  "chat.addContext": "添加上下文",
  "chat.permission": "权限",
  "chat.defaultPermission": "默认权限",
  "chat.fullPermission": "完全权限",
  "chat.selectPermission": "选择权限",
  "chat.selectModel": "选择模型",
  "chat.noEnabledModels": "没有启用的模型",
  "chat.modelHigh": "5.5 超高",
  "chat.send": "发送",
  "chat.stop": "停止生成",
  "chat.attachments": "附件",
  "chat.removeAttachment": "移除附件",
  "chat.addMenuTitle": "添加",
  "chat.addFile": "文件",
  "chat.addFileDescription": "从本地选择文件",
  "chat.addImage": "图片",
  "chat.addImageDescription": "从本地选择图片",
  "chat.unsupportedImageWarning": "当前模型不支持图片",

  "configuration.model": "模型",
  "configuration.modelSettings": "模型配置",
  "configuration.availableModels": "可用模型",
  "configuration.manageModels": "管理模型...",
  "configuration.availableModelList": "可用模型列表",
  "configuration.enableModelPrefix": "启用",
  "configuration.image": "图像",
  "configuration.text": "文本",
  "configuration.webSearch": "联网搜索",
  "configuration.searchMode": "搜索模式",
  "configuration.tavilyApiKey": "Tavily API Key（可选）",
  "configuration.modelManager": "管理模型",
  "configuration.priceNote": "价格以 “每 1k tokens” 为单位，不区分币种。",
  "configuration.newModel": "新建模型",
  "configuration.editModel": "编辑模型",
  "configuration.modelTable": "模型管理表",
  "configuration.tableModel": "模型",
  "configuration.tableImage": "图像",
  "configuration.tableInput": "输入/1k",
  "configuration.tableOutput": "输出/1k",
  "configuration.tableActions": "操作",
  "configuration.supported": "支持",
  "configuration.unsupported": "不支持",
  "configuration.edit": "编辑",
  "configuration.delete": "删除",
  "configuration.confirmDelete": "确定删除？",
  "configuration.cancel": "取消",
  "configuration.done": "完成",
  "configuration.modelId": "模型 ID",
  "configuration.modelIdPlaceholder": "例：claude-opus-4-7",
  "configuration.displayName": "显示名称",
  "configuration.displayNamePlaceholder": "留空则使用模型 ID",
  "configuration.inputPrice": "输入价格 / 1k tokens",
  "configuration.outputPrice": "输出价格 / 1k tokens",
  "configuration.supportsImageInput": "支持图像输入",
  "configuration.save": "保存",
} as const;

export type TranslationKey = keyof typeof zhCNTranslations;

export const translations: Record<AppLanguage, Record<TranslationKey, string>> = {
  "zh-CN": zhCNTranslations,
  "en-US": {
    "app.mainWorkspace": "Main workspace",
    "app.leftSidebar": "Left sidebar",
    "app.rightSidebar": "Right sidebar",
    "app.collapseLeftSidebar": "Collapse left sidebar",
    "app.expandLeftSidebar": "Expand left sidebar",
    "app.collapseRightSidebar": "Collapse right sidebar",
    "app.expandRightSidebar": "Expand right sidebar",
    "app.resizeLeftSidebar": "Resize left sidebar",
    "app.resizeRightSidebar": "Resize right sidebar",

    "sidebar.newConversation": "New chat",
    "sidebar.projects": "Projects",
    "sidebar.conversations": "Chats",
    "sidebar.emptyConversations": "No chats",
    "sidebar.settings": "Settings",
    "sidebar.moreConversationActions": "More chat actions",
    "sidebar.newConversationAction": "Create new chat",
    "sidebar.justNow": "Just now",
    "project.chooseProject": "Choose project",
    "project.searchProject": "Search projects",
    "project.newProject": "New project",
    "project.noProject": "No project",
    "project.folderInput": "Choose a local project folder",
    "project.moreActions": "More project actions",
    "project.newProjectConversation": "New chat in project",

    "rightSidebar.newPanel": "New panel",
    "rightSidebar.maximize": "Maximize right sidebar",
    "rightSidebar.tools": "Right sidebar tools",
    "rightSidebar.review": "Review",
    "rightSidebar.reviewDescription": "Review proposed edits and change sets",
    "rightSidebar.terminal": "Terminal",
    "rightSidebar.terminalDescription": "Run commands in the current workspace",

    "settings.navigation": "Settings navigation",
    "settings.backToApp": "Back to app",
    "settings.search": "Search settings",
    "settings.searchPlaceholder": "Search settings...",
    "settings.content": "Settings content",
    "settings.update": "Update",
    "settings.group.personal": "Personal",
    "settings.group.coding": "Coding",
    "settings.page.general": "General",
    "settings.page.appearance": "Appearance",
    "settings.page.configuration": "Configuration",
    "settings.page.usageBilling": "Usage and billing",
    "settings.page.environment": "Environment",

    "general.language": "Language",
    "general.languageDescription": "Configure the language used by the frontend.",
    "general.languageAria": "Application language",

    "appearance.description": "This is the appearance settings skeleton. Theme, fonts, density, and display preferences can be added later.",
    "environment.selectProject": "Select project",
    "environment.addProject": "Add project",
    "environment.deleteProject": "Delete project",
    "environment.folderInput": "Choose a local project folder",
    "environment.removeProjectTitle": "Remove {projectName}?",
    "environment.removeProjectDescription": "This will remove the project. Files on disk will not be deleted.",
    "environment.cancelRemoveProject": "Cancel",
    "environment.confirmRemoveProject": "Remove",
    "usageBilling.description": "This is the usage and billing skeleton. Usage, quotas, invoices, and subscription status can be added later.",

    "chat.newConversation": "New chat",
    "chat.title": "What should we build?",
    "chat.composer": "New chat composer",
    "chat.inputPlaceholder": "Ask anything",
    "chat.inputAria": "Enter a new task",
    "chat.addContext": "Add context",
    "chat.permission": "Permission",
    "chat.defaultPermission": "Default access",
    "chat.fullPermission": "Full access",
    "chat.selectPermission": "Select permission",
    "chat.selectModel": "Select model",
    "chat.noEnabledModels": "No enabled models",
    "chat.modelHigh": "5.5 High",
    "chat.send": "Send",
    "chat.stop": "Stop generating",
    "chat.attachments": "Attachments",
    "chat.removeAttachment": "Remove attachment",
    "chat.addMenuTitle": "Add",
    "chat.addFile": "Files",
    "chat.addFileDescription": "Choose local files",
    "chat.addImage": "Images",
    "chat.addImageDescription": "Choose local images",
    "chat.unsupportedImageWarning": "The current model does not support images",

    "configuration.model": "Models",
    "configuration.modelSettings": "Model configuration",
    "configuration.availableModels": "Available models",
    "configuration.manageModels": "Manage models...",
    "configuration.availableModelList": "Available models list",
    "configuration.enableModelPrefix": "Enable",
    "configuration.image": "Image",
    "configuration.text": "Text",
    "configuration.webSearch": "Web search",
    "configuration.searchMode": "Search mode",
    "configuration.tavilyApiKey": "Tavily API Key (optional)",
    "configuration.modelManager": "Manage models",
    "configuration.priceNote": "Prices are per 1k tokens and currency-neutral.",
    "configuration.newModel": "New model",
    "configuration.editModel": "Edit model",
    "configuration.modelTable": "Model management table",
    "configuration.tableModel": "Model",
    "configuration.tableImage": "Image",
    "configuration.tableInput": "Input/1k",
    "configuration.tableOutput": "Output/1k",
    "configuration.tableActions": "Actions",
    "configuration.supported": "Supported",
    "configuration.unsupported": "Unsupported",
    "configuration.edit": "Edit",
    "configuration.delete": "Delete",
    "configuration.confirmDelete": "Delete this model?",
    "configuration.cancel": "Cancel",
    "configuration.done": "Done",
    "configuration.modelId": "Model ID",
    "configuration.modelIdPlaceholder": "Example: claude-opus-4-7",
    "configuration.displayName": "Display name",
    "configuration.displayNamePlaceholder": "Leave empty to use model ID",
    "configuration.inputPrice": "Input price / 1k tokens",
    "configuration.outputPrice": "Output price / 1k tokens",
    "configuration.supportsImageInput": "Supports image input",
    "configuration.save": "Save",
  },
};
